// بيانات الحروف العربية
const lettersData = [
    { letter: 'أَ', word: 'أرنب', wordKey: 'arnab', emoji: '🐰' },
    { letter: 'بَ', word: 'بطة', wordKey: 'batta', emoji: '🦆' },
    { letter: 'تَ', word: 'تمرتين', wordKey: 'tamrteen', emoji: '🫐', image: 'تمرتين.png' },
    { letter: 'ثَ', word: 'ثلاجة', wordKey: 'thallaja', emoji: '🧸', image: 'ثلاجة.png' },
    { letter: 'جَ', word: 'جمل', wordKey: 'jamal', emoji: '🐪' },
    { letter: 'حَ', word: 'حمامة', wordKey: 'hamama', emoji: '🕊️' },
    { letter: 'خَ', word: 'خروف', wordKey: 'kharuf', emoji: '🐑' },
    { letter: 'دَ', word: 'دم', wordKey: 'dam', emoji: '🩸' },
    { letter: 'ذَ', word: 'ذيل', wordKey: 'dhayl', emoji: '🦎', image: 'ذيل.png' },
    { letter: 'رَ', word: 'رجل', wordKey: 'rajul', emoji: '👨', image: 'رجل.png' },
    { letter: 'زَ', word: 'زرافة', wordKey: 'zarafa', emoji: '🦒' },
    { letter: 'سَ', word: 'ساعة', wordKey: 'saaa', emoji: '⏰' },
    { letter: 'شَ', word: 'شجرة', wordKey: 'shajara', emoji: '🌳' },
    { letter: 'صَ', word: 'صقر', wordKey: 'saqr', emoji: '🦅' },
    { letter: 'ضَ', word: 'ضبع', wordKey: 'daba', emoji: '🐺' },
    { letter: 'طَ', word: 'طيارة', wordKey: 'tayara', emoji: '✈️' },
    { letter: 'ظَ', word: 'ظرف', wordKey: 'zarf', emoji: '✉️' },
    { letter: 'عَ', word: 'عين', wordKey: 'ayn', emoji: '👁️' },
    { letter: 'غَ', word: 'غزالة', wordKey: 'ghazala', emoji: '🦌' },
    { letter: 'فَ', word: 'فأر', wordKey: 'far', emoji: '🐭' },
    { letter: 'قَ', word: 'قلم', wordKey: 'qalam', emoji: '✏️' },
    { letter: 'كَ', word: 'كلب', wordKey: 'kalb', emoji: '🐕' },
    { letter: 'لَ', word: 'ليمون', wordKey: 'lemon', emoji: '🍋' },
    { letter: 'مَ', word: 'موز', wordKey: 'mooz', emoji: '🍌' },
    { letter: 'نَ', word: 'نخلة', wordKey: 'nakhla', emoji: '🌴' },
    { letter: 'هَ', word: 'هرم', wordKey: 'haram', emoji: '🔺' },
    { letter: 'وَ', word: 'وردة', wordKey: 'warda', emoji: '🌹' },
    { letter: 'يَ', word: 'يد', wordKey: 'yad', emoji: '✋' }
];
